### ISSUE TITLE
GH-Pages Deploy action needs user credentials set 

### ISSUE THREAD

**Issue by Brutalbeard** [RingCentral-Pro-Services/psi-validator.js#15]
Simple mistake on my part, but needs git credentials set. Can probably just use an access token for the repo.

**Comment by pachori-ujjwal** [comment]
Created a [pull request](https://github.com/RingCentral-Pro-Services/psi-validator.js/pull/17) for this.Added your email and name @Brutalbeard so that Github can show an author when the Github pages are published.

**Comment by Brutalbeard** [comment]
Whoops! My email for github is `jceloria@gmail.com`.

**Comment by pachori-ujjwal** [comment]
Created [another](https://github.com/RingCentral-Pro-Services/psi-validator.js/pull/18) one.

**Comment by Brutalbeard** [comment]
Well crud, similar error https://github.com/RingCentral-Pro-Services/psi-validator.js/runs/4460538263?check_suite_focus=true#step:8:36

**Comment by pachori-ujjwal** [comment]
And [once again](https://github.com/RingCentral-Pro-Services/psi-validator.js/pull/19) :joy:

**Comment by Brutalbeard** [comment]
Lol i'll change branch protection so you can do your own reviews if this one gives us a hard time

**Comment by pachori-ujjwal** [comment]
Looks like I am going to need maintainer access again to for the environment variables and stuff.

**Comment by Brutalbeard** [comment]
lol comin up

**Comment by Brutalbeard** [comment]
alright you're an admin, and branch protection no longer applies to repo admins

**Comment by Brutalbeard** [comment]
@pachori-ujjwal looks like we forgot to close this
