### ISSUE TITLE
Setup NPM for relasing as package

### ISSUE THREAD

**Issue by Brutalbeard** [RingCentral-Pro-Services/psi-validator.js#9]
Want to be able to use releases to setup npmjs.org

I think that @pachori-ujjwal might've started this process a while ago

**Comment by pachori-ujjwal** [comment]
Yup @Brutalbeard the first version was published and can be visited [here](https://www.npmjs.com/package/psi-validator). The package will be auto-published as soon as a release is published here in Github.

**Comment by Brutalbeard** [comment]
@pachori-ujjwal ballin. I'm closin this then
